### ISSUE TITLE
Constant Vibration

### ISSUE THREAD

**Issue by Exuno** [6zs/fibble#1]
I've been playing a lot of fibble but as of today it seems to now vibrate and warn me to beware the lies on every single input; while this is maybe charming the first time I open it; it's extremely distracting and unpleasant if I'm going to sit down and do unlimited for like 20 minutes to try to unwind.

Not sure there was anywhere else to provide feedback, sorry if this isn't the best place

**Comment by 6zs** [comment]
ok, i've got rid of the animation entirely for now and the text about lies only shows up in daily puzzles, and only until you've played a few clues. the main thing this was trying to solve is that some people play xordle then fibble, and get confused as to which they're playing, trying to guess 2 words in fibble

**Comment by Exuno** [comment]
Yeah, that's definitely understandable; they're both a lot of fun and I bounce between them and the similar site designs can get confusing. I probably wouldn't object to it happening only on the first guess of the daily puzzle specifically, and that should be a pretty good signal.

Connecting to my other comment, having larger lie icons on each row would also be a pretty good reminder - possibly even making them like a very obvious red strikeout overlay or something. (Though I guess you still would want to see the letter, so maybe it would have to be a diamond or something...) EDIT: or do tricky layering! the letter can be on top and always white, and the cross can just override the BG color!
