### ISSUE TITLE
Two Errors in One Row

### ISSUE THREAD

**Issue by SwagapottamusRex** [6zs/fibble#11]
Fibble Unlimited 8787 X/8 2/2🏴
⬛⬛🟩⬛⬛
🟨⬛⬛⬛⬛
🟩⬛⬛⬛🟨
🟨🟩🟨⬛⬛
⬛⬛⬛⬛🟨
⬛⬛⬛⬛⬛
⬛🟨⬛🟩🟨
🟨⬛⬛🟨🟨
⬛🟨🟨🟨⬛
https://fibble.xyz/?unlimited=8787
<img width="377" alt="Screenshot 2024-09-07 at 19 12 54" src="https://github.com/user-attachments/assets/11b28a3e-714e-49a3-9468-79d3b2217d35">
<img width="317" alt="Screenshot 2024-09-07 at 19 11 12" src="https://github.com/user-attachments/assets/1a308978-785a-44a3-84e3-9288c0e8221b">

Two lies in one row. (two e's) - row 5.

**Comment by kellydornhaus** [comment]
This trips people up a lot and could be better explained but it is not an error. The correct wordle clue is a yellow E followed by a grey E. A fibble clue is a wordle clue where the color of one of the letters has been changed. This does mean you really need to look out when you use double letters.

**Comment by SwagapottamusRex** [comment]
I see. Thanks for the explanation. I get it now.
