### ISSUE TITLE
Request: Mark Truths

### ISSUE THREAD

**Issue by Exuno** [6zs/fibble#2]
While marking the lie in each row is an extremely useful feature, it's also tricky and frustrating when it's narrowed down to, say, one of two positions. Having some alternative that could help me remember the three letters that _must_ be valid clues for the solution would be really nice in these situations - rather than having to bounce the flags back and forth between two complex chains of possibilities and try to juggle all that in my head.

**Comment by 6zs** [comment]
it may take me a while to get to this, but my thinking is that right click or long-press a tile could put a padlock on it. if it's unflagged that means it's true, and if it's flagged that means it's false (and not being used speculatively). does that sound like it would work?

**Comment by Exuno** [comment]
Hmm, I'm not totally seeing how that works in my mind's eye from that description, but maybe rephrasing it would help it make more sense.

Thinking about it from what would feel natural (and fast!) to me - despite it being a slight controls change - is making a short press/left click toggle between 'uncertain' (default, no icon) and 'trustworthy' (lock or thumbs up or idk).

Marking lies would be the slower option (because it requires more information to do) and I'd suggest making the flags larger, draggable icons that could be dropped onto letters when you're confident they were incorrect. Tapping the original spot they started could reset it; and right click and long-press are valid alternate controls as well.

**Comment by Exuno** [comment]
Giving the keyboard letters a border or something when it's color is marked as verified somewhere would be a neat touch, too!

**Comment by Exuno** [comment]
I used today's puzzle to make a mockup of what I was thinking in this and the other thread about UX design - a basic check seems like it's mostly alright with most forms of impaired color vision (but would definitely need some tweaks for high contrast mode).

Probably should have used an unlimited instead of spoiling today's puzzle but oh well, hopefully no one is checking github on this specific day before doing the puzzle.

![image](https://user-images.githubusercontent.com/27643668/169759322-93ce63e5-74d8-49c8-a818-dfac902d1547.png)

**Comment by 6zs** [comment]
that looks pretty good! 

i added a really basic thing today. it's just right click to highlight a tile. it doesn't have any effect on the keyboard (yet) nor any mobile control, just want to see how it feels.

btw you said marking lies takes more information than truths. technically true, but i don't know if it matches how people use the flags in practice. personally, i liberally mark things as lies in a speculative fashion, then i make a guess that fits the lies i've marked. i don't wait until i know something is a lie to start marking it.

when i look at your mock up, it kind of make me want to:
  - get rid of the flags and replace them with these red underlay Xs
  - right click a tile to "lock it in". if it's a truth it displays a light blue border (and keyboard updates accordingly). if it's flagged/X'd it displays a dashed black border (like the final puzzle does on the actual lies).
  - maybe: when you lock in a lie, it auto-toggles the rest of the rows to locked-in truths

**Comment by 6zs** [comment]
i'm enjoying the current implementation. please reopen if it doesn't fit your needs!
