### ISSUE TITLE
Error with color markings?

### ISSUE THREAD

**Issue by Liannn1303** [6zs/fibble#3]
Hi, I encountered this while playing. Is this the correct behavior? I believe these Ms should not be gray as there is an M in the word. They should both have been yellow, right?
![Screenshot_20220520-201413_Chrome](https://user-images.githubusercontent.com/33220273/169589539-4dd9139a-2abc-4094-a9da-87383ffd23ba.jpg)

**Comment by Liannn1303** [comment]
![Screenshot_20220520-220243_Chrome](https://user-images.githubusercontent.com/33220273/169603145-000cc6f7-23ea-4ffa-80ad-2d7cae2c7203.jpg)
Again another example, where there are grey letters which should have been yellow if they were true

**Comment by Liannn1303** [comment]
Nevermind, I misunderstood the explanation. They are only grey as there is already a clue.

**Comment by Exuno** [comment]
Yeah, there's a couple of really tricky ways the cluing logic can work, and you should remember it all happens _before_ the lie.

While getting that 'there's only one M, so the others are grey' is simple in your first example; there's a few other tricks you can use to catch onto the lies elsewhere.

In two cases the word SASSY has the middle S in yellow - you can be instantly sure this is the work of a lie. Yellow letters always work left-to-right. If there was a single S in the answer, the leading S would be yellow and the second and third would be grey. 

Either 1. the starting S is a lie, and there are two Ss, neither in the third position (the first could be green or yellow), 2.  the middle S is supposed to be Green, and is the only S (true for RUSTY) or 3. the middle S is supposed to be grey, and there are no Ss. (true for METAL).

This may seem to be a lot of options, but it does mean the 2nd, 4th, and 5th letters are 100% trustworthy, and other guesses can usually eliminate some of the possibilities.
